[build-system]
requires = [
    "setuptools>=83.0.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "robotframework-mbt"
version = "1.0.0"
description = "Model-Based Testing in Robot Framework with test case generation"
readme = "README.md"
authors = [{ name = "Johan Foederer", email = "github@famfoe.nl" }]
license = "BSD-3-Clause"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["robotframework", "robot", "mbt", "bdd", "testing"]
dependencies = [
    "robotframework >= 7.3",
]
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["robotmbt*"]

[project.urls]
Homepage = "https://github.com/JFoederer/robotframeworkMBT"

[project.optional-dependencies]
full = ["networkx", "bokeh", "grandalf", "jsonpickle"]
